- name: Setup QuestPlanner Server
  hosts: localhost
  connection: local

  tasks:
    - name: Update system
      command: apt update

    - name: Install Docker
      command: apt install docker.io -y

    - name: Start Docker
      command: systemctl start docker

    - name: Run project
      command: docker compose up -d --build
      args:
        chdir: /home/nurlybek
